name: Automated Image Scraper Demo

on:
  workflow_dispatch:
  schedule:
    # Runs daily at midnight UTC.
    - cron: '0 0 * * *'

jobs:
  scrape-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run image scraper
        env:
          # These secrets must be configured in your repository settings
          # Go to Settings > Secrets and variables > Actions to add them.
          API_USERNAME_1: ${{ secrets.API_USERNAME_1 }}
          API_PASSWORD_1: ${{ secrets.API_PASSWORD_1 }}
          API_USERNAME_2: ${{ secrets.API_USERNAME_2 }}
          API_PASSWORD_2: ${{ secrets.API_PASSWORD_2 }}
        run: |
          source venv/bin/activate
          python -u image_scraper.py
      
      - name: Commit progress
        if: always()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add downloaded-images.csv
          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "feat: Update image download progress"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Archive image results
        if: always()
        run: |
          zip -r product-images-archive.zip product-images downloaded-images.csv
      
      - name: Upload image artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: product-images-archive
          path: product-images-archive.zip 