name: Image Scraper

on:
  workflow_dispatch:
  schedule:
    # Runs at the start of every hour.
    - cron: '0 * * * *'

jobs:
  scrape-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the action to commit to the repository
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run image scraper
        id: scraper
        env:
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
          API_USERNAME_2: ${{ secrets.API_USERNAME_2 }}
          API_PASSWORD_2: ${{ secrets.API_PASSWORD_2 }}
        run: |
          source venv/bin/activate
          python -u image_scraper.py
      
      - name: Commit progress
        if: always()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add downloaded-images.csv
          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "feat: Update image download progress"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Archive image results
        if: always()
        run: |
          zip -r zt-image-fetch.zip tsa-images downloaded-images.csv
      
      - name: Upload image artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tsa-image-fetch-results
          path: tsa-image-fetch.zip 