name: Image Scraper

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  scrape-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the action to commit to the repository
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # We need to fetch all history to be able to push
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run image scraper
        id: scraper
        env:
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
          API_USERNAME_2: ${{ secrets.API_USERNAME_2 }}
          API_PASSWORD_2: ${{ secrets.API_PASSWORD_2 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        run: |
          source venv/bin/activate
          python -u image_scraper.py

      - name: Continue execution
        if: always() && steps.scraper.outputs.work_done == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Work is not done. Triggering next workflow run."
          gh workflow run "${{ github.workflow }}" --ref ${{ github.ref_name }} 